import type { Application } from "@/types/petsType"

export const sampleApplications: Application[] = [
  {
    id: "1",
    petId: "1",
    petName: "Luna",
    applicantName: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
    address: "123 Oak Street, San Francisco, CA 94102",
    experience: "I have had dogs for over 10 years and currently have a fenced backyard.",
    reason: "Looking for a companion for my family and our current dog.",
    status: "pending",
    dateSubmitted: "2024-01-16",
    applicantImage: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "2",
    petId: "2",
    petName: "Whiskers",
    applicantName: "Michael Chen",
    email: "michael.chen@email.com",
    phone: "(555) 987-6543",
    address: "456 Pine Avenue, Los Angeles, CA 90210",
    experience: "First-time pet owner but have researched extensively about cat care.",
    reason: "Want to provide a loving home for a cat in need.",
    status: "approved",
    dateSubmitted: "2024-01-14",
    applicantImage: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "3",
    petId: "3",
    petName: "Max",
    applicantName: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    phone: "(555) 456-7890",
    address: "789 Maple Drive, New York, NY 10001",
    experience: "Volunteer at local animal shelter for 3 years.",
    reason: "Looking for a loyal companion for hiking and outdoor activities.",
    status: "pending",
    dateSubmitted: "2024-01-13",
    applicantImage: "/placeholder.svg?height=40&width=40",
  },
]
