import type { Pet } from "@/types/petsType"

export const samplePets: Pet[] = [
  {
    id: "1",
    name: "Luna",
    species: "Dog",
    breed: "Golden Retriever",
    age: "2 years",
    gender: "Female",
    size: "Large",
    color: "Golden",
    description:
      "Luna is a friendly and energetic dog who loves playing fetch and swimming. She's great with kids and other pets.",
    image: "/placeholder.svg?height=300&width=300",
    status: "available",
    location: "San Francisco, CA",
    dateAdded: "2024-01-15",
    vaccinated: true,
    spayed: true,
  },
  {
    id: "2",
    name: "Whiskers",
    species: "Cat",
    breed: "Persian",
    age: "3 years",
    gender: "Male",
    size: "Medium",
    color: "White",
    description: "Whiskers is a calm and affectionate cat who enjoys quiet environments and gentle petting.",
    image: "/placeholder.svg?height=300&width=300",
    status: "pending",
    location: "Los Angeles, CA",
    dateAdded: "2024-01-10",
    vaccinated: true,
    spayed: true,
  },
  {
    id: "3",
    name: "Max",
    species: "Dog",
    breed: "German Shepherd",
    age: "4 years",
    gender: "Male",
    size: "Large",
    color: "Brown & Black",
    description:
      "Max is a loyal and intelligent dog, perfect for an active family. He knows basic commands and is house-trained.",
    image: "/placeholder.svg?height=300&width=300",
    status: "available",
    location: "New York, NY",
    dateAdded: "2024-01-08",
    vaccinated: true,
    spayed: true,
  },
  {
    id: "4",
    name: "Bella",
    species: "Cat",
    breed: "Siamese",
    age: "1 year",
    gender: "Female",
    size: "Small",
    color: "Cream & Brown",
    description: "Bella is a playful kitten who loves toys and climbing. She's very social and loves attention.",
    image: "/placeholder.svg?height=300&width=300",
    status: "available",
    location: "Chicago, IL",
    dateAdded: "2024-01-12",
    vaccinated: true,
    spayed: false,
  },
]
